services:
  metatool-web:
    container_name: metatool-web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - stack.env
    restart: always
    ports:
      - '12005:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - metatool-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  metatool-postgres:
    container_name: metatool-postgres
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: metatool
      POSTGRES_USER: metatool
      POSTGRES_PASSWORD: m3t4t00l
    ports:
      - '8432:5432'
    volumes:
      - metatool-postgres:/var/lib/postgresql/data

  drizzle-migrate:
    container_name: drizzle-migrate
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    command: pnpm drizzle-kit migrate
    env_file:
      - stack.env
    depends_on:
      - metatool-postgres

volumes:
  metatool-postgres:
    driver: local

networks:
  default:
    external:
      name: bridge
